#!/bin/bash

LICENCE="Logic Analyzer RPi ChangeLog -- History of user-visible changes

	Copyright (C) 2012,2013 Renier Yves
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
    
This file is automaticaly generated by ./gen_changelog.sh

"
echo "generate ChangeLog from git log"
top_srcdir=$1
distdir=$2
if [ $(cat ${distdir}/ChangeLog | wc -l ) == "1" ]; then
	chmod u+w ${distdir}/ChangeLog && \
	echo $LICENSE> ${distdir}/ChangeLog && \
	git log --stat --name-only --date=short --abbrev --decorate >> ${distdir}/ChangeLog
	
fi
